export enum Genre {
  FICTION = 'Fiction',
  NONFICTION = 'Nonfiction',
  SCIENCE_FICTION = 'Science Fiction',
  FANTASY = 'Fantasy',
  BIOGRAPHY = 'Biography',
  MYSTERY = 'Mystery',
  THRILLER = 'Thriller',
  ROMANCE = 'Romance',
  HORROR = 'Horror',
  HISTORY = 'History',
  POETRY = 'Poetry',
  DRAMA = 'Drama',
  ADVENTURE = 'Adventure',
  CHILDRENS = "Children's",
  YOUNG_ADULT = 'Young Adult',
  SELF_HELP = 'Self-Help',
  RELIGION = 'Religion',
  COOKING = 'Cooking',
  ART = 'Art',
  TRAVEL = 'Travel',
}
