package com.xtramile.library2024.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookStorageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookStorageAllPropertiesEquals(BookStorage expected, BookStorage actual) {
        assertBookStorageAutoGeneratedPropertiesEquals(expected, actual);
        assertBookStorageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookStorageAllUpdatablePropertiesEquals(BookStorage expected, BookStorage actual) {
        assertBookStorageUpdatableFieldsEquals(expected, actual);
        assertBookStorageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookStorageAutoGeneratedPropertiesEquals(BookStorage expected, BookStorage actual) {
        assertThat(expected)
            .as("Verify BookStorage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookStorageUpdatableFieldsEquals(BookStorage expected, BookStorage actual) {
        assertThat(expected)
            .as("Verify BookStorage relevant properties")
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookStorageUpdatableRelationshipsEquals(BookStorage expected, BookStorage actual) {
        assertThat(expected)
            .as("Verify BookStorage relationships")
            .satisfies(e -> assertThat(e.getLibrary()).as("check library").isEqualTo(actual.getLibrary()));
    }
}
